[change] Breaking Change: Refactored API endpoints #106
openwisp/openwisp-ipam pull request #107
Opened 2021-05-20 21:17 UTC by pandafy

Changed API endpoints from "/api/v1/*" to "/api/v1/ipam/*"

Fixes #106

2021-05-20 21:18 UTC, pandafy commented on openwisp_ipam/api/__init__.py
> -from django.urls import path
This does not seem to be the right place for URLs. I had to look for them, hence moved them to a dedicated file.

2021-05-21 15:15 UTC, nemesisdesign requested changes
As commit prefix please use `[change!]`, the exclamation mark stands for backward incompatible.

2021-05-26 02:05 UTC, nemesisdesign requested changes
Please **always** do some minimal manual testing before submitting PRs.

![Screenshot from 2021-05-25 21-04-24](https://user-images.githubusercontent.com/841044/119591776-d9b50880-bd9c-11eb-87ac-9cc7cd695401.png)

2021-05-27 01:45 UTC, nemesisdesign approved these changes

2021-05-27 01:46 UTC, merged