[docs] Added instruction for using virtualenv
openwisp/openwisp-ipam pull request #177
Opened 2024-12-18 18:21 UTC by youhaveme9

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [x] I have updated the documentation.

## Reference to Existing Issue

Closes #170 

## Description of Changes

Recommend using [Python Virtualenv](https://virtualenv.pypa.io/en/latest/) in development instructions.

2024-12-19 06:27 UTC, pandafy requested changes

2024-12-19 06:27 UTC, pandafy commented on docs/developer/installation.rst
> +
Can you make these steps consistent with what we have in [openwisp-controller](https://github.com/openwisp/openwisp-controller/blob/455144437b947fa343e39e0cea33ca997782f369/docs/developer/installation.rst?plain=1#L46-L52)?

2024-12-19 07:29 UTC, youhaveme9 commented
Updated the docs as required

2024-12-20 07:13 UTC, pandafy approved these changes

2024-12-20 07:47 UTC, merged