[bug] Fix exception in api #71
openwisp/openwisp-ipam pull request #74
Opened 2020-11-11 17:51 UTC by Purhan

Closes #71

2020-11-11 17:56 UTC, Purhan commented
@nemesisdesign I'm not sure if these are the desired changes. Please take a look whenever possible and suggest changes if required :smile:

2020-11-13 07:04 UTC, devkapilbansal reviewed
@Purhan instead of bug the type should be fix

2020-11-13 07:08 UTC, Purhan commented
> @Purhan instead of bug the type should be fix

@devkapilbansal Could you elaborate what you mean by 'type'?

2020-11-13 09:04 UTC, devkapilbansal commented
> > @Purhan instead of bug the type should be fix
> 
> @devkapilbansal Could you elaborate what you mean by 'type'?

In commit message you have included [bug] in title, it should be [fix]

2020-11-20 15:58 UTC, nemesisdesign requested changes
One change requested and then we can merge, thanks @Purhan

2020-11-20 15:58 UTC, nemesisdesign commented on openwisp_ipam/api/views.py
> +            raise serializers.ValidationError({'detail': 'Invalid Address'})
please make `Invalid Address` translatable

2020-11-20 16:45 UTC, Purhan commented on openwisp_ipam/api/views.py
> +            raise serializers.ValidationError({'detail': 'Invalid Address'})
@nemesisdesign done

2020-11-20 17:24 UTC, nemesisdesign approved these changes
Thanks @Purhan :+1:

2020-11-20 17:24 UTC, merged