[feature] Allow shared subnets to have non shared child subnets #90
openwisp/openwisp-ipam pull request #92
Opened 2021-03-31 14:54 UTC by pandafy

Closes #90

2021-04-01 04:42 UTC, nemesisdesign reviewed
can you rebase on the current master and see my comment below?

2021-04-01 04:42 UTC, nemesisdesign commented on openwisp_ipam/base/models.py
> +            if self.master_subnet.organization_id is None:
this works if there's only 1 level, but may not work if the master subnet does have an org set but has itself a relation to another master subnet which is shared, that's why in one of the validation checks below we iterate over all the master subnets

2021-04-14 01:24 UTC, nemesisdesign requested changes
Tested and works. I am not sure it will work with nested master subnets, if you can check it would be great, if it doesn't work we can create an issue to deal with that later on.

Please fix the conflict and solve the issue highlighted in the comment below.

2021-04-15 11:47 UTC, pandafy commented
@nemesisdesign did you mean to test this? 
![image](https://user-images.githubusercontent.com/32094433/114862708-7b475280-9e0c-11eb-9d15-39cac6a0bb60.png)

Coverage seem to go down for unrelated reason.

2021-04-15 18:33 UTC, nemesisdesign commented
> @nemesisdesign did you mean to test this?
> ![image](https://user-images.githubusercontent.com/32094433/114862708-7b475280-9e0c-11eb-9d15-39cac6a0bb60.png)

Yes, does it work?
Is there a test for it?
 
> Coverage seem to go down for unrelated reason.

Ok, let's ignore it now, I created an issue for this: https://github.com/openwisp/openwisp-ipam/issues/96

2021-04-16 11:15 UTC, pandafy commented
> Is there a test for it? 

I have added a test for it.

2021-04-17 01:49 UTC, nemesisdesign approved these changes
Thanks!

2021-04-17 01:49 UTC, merged